name: MonSuperPlugin
version: 1.0
author: AlexandreLG2022
main: fr.alexandrelg2022.monSuperPlugin.Main
description: Un super plugin pour un super serveur !
website: https://alex-development.eu
commands:
  nick:
    description: Change your username in the server.
    usage: /nick <username>
    permission: msp.features.nick
  invsee:
    description: Open another player inventory.
    usage: /invsee <player>
    permission: msp.features.invsee